### ISSUE TITLE
Benchmarks should not use assert

### ISSUE THREAD

**Issue by jeremybennett** [embench/embench-iot#10]
Jon Taylor pointed out that assert is not appropriate for benchmarks. See the full mailing list discussion here:

https://lists.librecores.org/pipermail/embench/2019-August/000007.html

I consider this a bug, and this issue is to track a fix to the problem.

**Comment by jeremybennett** [comment]
Pull request to fix this in https://github.com/embench/embench-iot/pull/11.

**Comment by jeremybennett** [comment]
Marking as closed since this has now been fixed.

**Comment by fanghuaqi** [comment]
Hi @jeremybennett , according the benchmark code should avoid using assert rule, for this line https://github.com/embench/embench-iot/blob/master/support/beebsc.c#L65 

`  assert(heap_size % sizeof(void *) == 0);  /* see #138 */`  may need to change to   `assert_beebs(heap_size % sizeof(void *) == 0);  /* see #138 #10  *//`
