### ISSUE TITLE
Does Embench support RISCV64 ISA

### ISSUE THREAD

**Issue by mollybuild** [embench/embench-iot#159]
Embench supports RISCV-32 ISA. But how about RISCV64? Does it support it now? Thanks.

**Comment by jeremybennett** [comment]
@mollybuild 64-bit RISC-V is not currently supported, but we would welcome a pull-request to add support.

It's worth noting that Embench IoT is aimed at small embedded microcontrollers.  These are typically 32-bit or smaller, so 64-bit RISC-V would be untypical. But support would still be welcome.

I'm marking as closed, but please reopen if you would like to discuss further.  Alternatively attend one of our monthly videoconferences to ask a question and discuss.  Upcoming dates in 2022 are:

- Mon 25 Apr 2022
- Mon 16 May 2022
- Mon 20 Jun 2022
- Mon 18 Jul 2022
- Mon 15 Aug 2022
- Mon 19 Sep 2022
- Mon 17 Oct 2022
- Mon 21 Nov 2022
- Mon 12 Dec 2022

All held at 08:00 Pacific Time.  Agenda and videoconference details published on the [mailing list](https://lists.librecores.org/listinfo/embench) shortly before.
