### ISSUE TITLE
Formatted string literals is not supported in Python3.5

### ISSUE THREAD

**Issue by quxianmiao** [embench/embench-iot#20]
The formatted string literals is a feature of Python 3.6. For instance, the following code written in the build_all.py:
               log.error(f'ERROR: Architecture "{args.arch}" not found: exiting')

If the code does not support versions below Python 3.6, this is not a problem, but it needs to be declared.

**Comment by jeremybennett** [comment]
@quxianmiao Sorry for the slow reply while I have been away.

The scripts are written assuming at least Python 3.6. I'm working on a patch which will check the python version at the start of each script.

**Comment by jeremybennett** [comment]
@quxianmiao Fixed in pull request 25. Can you check this works for you.
