### ISSUE TITLE
Problems with spaces when setting tool flag options

### ISSUE THREAD

**Issue by MarkHillHuawei** [embench/embench-iot#51]
I have noticed that if a user puts extra spaces in their tool options, for example, --cflags “-Os<space><space>–mtune=size” instead of --cflags “-Os<space>–mtune=size” the build fails complaining about a non existent file. This can be a bit confusing, it certainly confused me until I realized what was going on.   This is  due to the split(sep=’ ‘) in build_all.py creating empty elements in the cflags list e.g. [ ‘-Os’, ‘’, ‘-mtune=size’ ].

I think all the split(sep=' ') commands just need to be split() which ignores multiple spaces by default.

**Comment by jeremybennett** [comment]
Hi @MarkHillHuawei ,

Thanks for raising this. I'll inviestigate.

Best wishes,

Jeremy

**Comment by PaoloS02** [comment]
Thank you for the tip @MarkHillHuawei ,
fixed that now.

Kind regards,
Paolo

**Comment by PaoloS02** [comment]
The fix is on master. I would close this issue.

Thank you again.
Paolo
